### ISSUE TITLE
Tabs: Presque impossible de cliquer en vue responsive

### ISSUE THREAD

**Issue by CorentinHcd** [SNCFdevelopers/bootstrap-sncf#137]
Bonjour,

Lors de l'utilisation du mode responsive avec les [Tabs,](https://designmetier-bootstrap.sncf.fr/docs/4.0/layout/navs/#tabs) il m'est presque impossible de cliquer sur les navtabs-item, il y a doit y avoir un pixel de disponible pour cliquer dessus mais pas plus, il est alors très complexe de cliquer sur les éléments.

**Comment by nicolaswurtz** [comment]
Alors il semblerait que le problème vienne du comportent « dragscroll », la possibilité de scroller horizontalement en vue mobile, ça inhibe la possibilité de cliquer sur les onglets.
Si on supprime la classe « dragscroll » alors ça refonctionne : mais y'a plus de scroll des onglets en vue mobile.

**Comment by nicolaswurtz** [comment]
J'ai supprimé e.preventDefault() dans dragscroll.js qui doit empêcher l'action initiale du clic, inutile dans les deux cas où l'on utilise dragscroll dans Bootstrap-SNCF : les onglets et tables.
A priori, pas d'effets de bord, sinon on réouvre ;)
