### ISSUE TITLE
Select: Asynchrone + réinitialisation (selectExclusive.js)

### ISSUE THREAD

**Issue by CorentinHcd** [SNCFdevelopers/bootstrap-sncf#138]
Bonjour,

Je n'arrive pas à faire marcher les [select](https://designmetier-bootstrap.sncf.fr/docs/4.0/components/select/#default) avec des subjects sur Angular, il va bien récupérer les données mais les select vont marcher de façon très aléatoire... 

De même, il m'est impossible de réinitialiser un select.

**Comment by nicolaswurtz** [comment]
Alors première étape en ajoutant un event listener à chaque click pour reconstruire l'objet ça semble fonctionner mais il faut ensuite deux click pour choisir un item ce qui n'est pas satisfaisant.

De plus, dans le comportement normal de l'objet, il **faut** avoir une option « cachée » `<option selected data-role="default-hidden-option" disabled hidden>Lorem ipsum</option>` relative au _placeholder_ pour que le décompte du choix se fasse comme il faut ce qui n'est pas hyper évident de prime abord.
