### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by CorentinHcd** [SNCFdevelopers/bootstrap-sncf#139]
Bonjour,

Lorsque je veux réinitialiser la date du datepicker via un formulaire, cela réinitialise bien la date mais le rond bleu qui sert à dire quelle date est active reste à la précédente date, je m'explique : 

Lorsque l'on sélectionne une date supérieure à la date d'aujourd'hui on ouvre une popup comme quoi il faut choisir une date inférieure et on réinitialise la date a ce qu'il avait précédemment sélectionné, malheureusement, le rond bleu reste sur la mauvaise date...

Bonne journée

**Comment by nicolaswurtz** [comment]
Est-ce qu'en allant consulter la doc de l'outil intégré, tu pourrais peut-être voir ce qu'il ne va pas ? logiquement nous n'avons modifié que la partie CSS https://flatpickr.js.org/
