### ISSUE TITLE
[Feature request] Suggestion d'un nouveau composant : accordéon 

### ISSUE THREAD

**Issue by clementmeni** [SNCFdevelopers/bootstrap-sncf#142]
Dans le cadre du développement d'un nouvel écran pour la FAB SSI, j'aimerais implémenté l'équivalent d'un accordéon. Voir l'image en pièce jointe : 
Est-ce qu'il est possible d'avoir ce composant ?

Merci

![vue role rssi liste equipe](https://user-images.githubusercontent.com/35597344/48834873-12fcff80-ed7f-11e8-8013-554ed96aee62.png)

**Comment by jroquillet** [comment]
Hello @clementmeni, je vais regarder avec Charly si on a ce cas là autre part. Mais c'est dommage, ça te fait cliquer un peu partout. 
Sorry pour le temps de réponse, j'étais passé à côté de l'issue... Pour les prochaines fois, ce que je peux te conseiller c'est : 
- l'utilisation des chips https://designmetier-bootstrap.sncf.fr/docs/4.0/components/forms/#chips
- avoir un fonctionnement un peu plus linéaire un peu sur le même principe que la gestion d'une équipe sur Teams :)
