### ISSUE TITLE
[URGENT][Partial Fix] DateTimePicker : ne fonctionne pas sur webkit/mobile

### ISSUE THREAD

**Issue by nicolaswurtz** [SNCFdevelopers/bootstrap-sncf#147]
Le comportement normal de flatpickrjs est de substituer la version native du picker quand on est sur mobile. Pour ce faire, il met l'input original en type="hidden" et en crée un nouveau du type demandé (eg. type="date").
Ce comportement est bien visible dans l'inspecteur mais sur mobile webkit, chrome/android, safari+chrome/ios et sur chrome en vue responsive le placeholder disparaît, et le champ ne réagit pas au click, rien ne se passe.

**Comment by CorentinHcd** [comment]
Je rajoute un commentaire sur le fait qu'il est fonctionnel sur iPad ( c'est à dire quand on clique sur le champ ) sauf quand on clique sur le bouton bleu.

**Comment by vdesdoigts** [comment]
Vu avec Nicolas, celui-ci fonctionne mais il faudrait que la version mobile soit native.

**Comment by vdesdoigts** [comment]
Une résolution de type mobile ou tablette n'a pas vocation à être utilisée sur un écran desktop.
Néanmoins, le datepicker actuel fonctionne correctement sur toutes les résolutions non ?

**Comment by CorentinHcd** [comment]
Sur iPad il fonctionne quand on clique sur le champ blanc mais pas sur le bouton bleu, sur Iphone il marche aléatoirement quand on clique sur le champ blanc, je fais des tests sur android (tablette et telephone) cet aprem pour confirmer ;)

**Comment by diyfr** [comment]
Anomalie non corrigée par la pr #151 @vdesdoigts 
La librairie flatpickr remplace bien le composant web par un input classique de type date lorsque l'on est sur mobile, donc le navigateur mobile devrait afficher le composant calendrier natif  
Sauf que l'événement click doit-être à priori cactché en amont bloquant l'appel du composant natif.  
On peut éventuellement désactiver l'appel au composant natif  [disableMobile:true](https://flatpickr.js.org/mobile-support/)  en attendant une solution ?

**Comment by nicolaswurtz** [comment]
Je confirme, rien à faire ça veut pas. On laisse pour l'instant à disableMobile:true le temps qu'on trouve une solution.

**Comment by nicolaswurtz** [comment]
Effectivement, tout est résolu avec la mise à jour de la lib. Intégré et mergé dans `dev`.
