### ISSUE TITLE
Modals ne se ferment pas lorsqu'on change d'onglet

### ISSUE THREAD

**Issue by Latiatcha** [SNCFdevelopers/bootstrap-sncf#159]
Bonjour,
Problème rencontré lors d'une modale ouverte, elle est placée **en dessous** des barres de menus et donc lors d'une navigation le backdrop de la modal ne se ferme plus.

Soit modifier les z-index de la modal et du backdrop pour la placer tout au dessus des menus pour éviter à l'utilisateur de naviguer pendant une modale ouverte.
Soit fermer la modale lors d'une action hors de la modale.

Modal aujourd'hui = 
![capture](https://user-images.githubusercontent.com/26218680/50331471-08a95f00-04ff-11e9-927d-fea012808be8.PNG)

1ère solution en modifiant les z-index =
![solution1](https://user-images.githubusercontent.com/26218680/50331547-4b6b3700-04ff-11e9-9f14-791ece134bba.PNG)

**Comment by diyfr** [comment]
Le plus simple effectivement est de surcharger le Css en changeant la valeur du z-index.

**Comment by nicolaswurtz** [comment]
A priori c'est un comportement normal — voulu — car on fait la différence entre le contenu et les barres de navigation, c'est logique qu'en touchant aux navbars cela n'impacte pas le contenu, comme une modale lancée, en suivant la manière dont le design est pensé.

Après, suivant ton cas d'usage rien ne t'empêche effectivement d'assigner un `data-dismiss="modal"` sur l'un ou l'autre bouton.

Je ferme l'issue mais à discuter si jamais c'était trop contraignant (c'est possible que notre vision de cette logique soit erronée ;)
