### ISSUE TITLE
Problème de compatibilité IE 11

### ISSUE THREAD

**Issue by arisrais** [SNCFdevelopers/bootstrap-sncf#163]
Pour la compatibilité avec IE11, Il faut insérer la balise meta suivante sur l'ensemble de vos pages : 
`<meta http-equiv="X-UA-Compatible" content="IE=edge">`

Il faudrait l'indiquer dans la section "[Starter template](https://designmetier-bootstrap.sncf.fr/docs/4.0/getting-started/introduction/#starter-template)"

**Comment by diyfr** [comment]
A ajouter également sur les pages de documentation
