### ISSUE TITLE
Bug responsive sur la "Galactic bar"

### ISSUE THREAD

**Issue by arisrais** [SNCFdevelopers/bootstrap-sncf#165]
Le responsive sur la "Galactic bar" ne semble pas fonctionner correctement : 

![header-galactic](https://user-images.githubusercontent.com/10925147/51999482-2f25c700-24bb-11e9-8f9b-82a671aa7317.PNG)

**Comment by arisrais** [comment]
Constaté sur chrome (Windows) version 60.0.3112.78

**Comment by diyfr** [comment]
Je clos l'issue pour éviter les doublons
