### ISSUE TITLE
Menu mobile Bootstrap communication

### ISSUE THREAD

**Issue by Latiatcha** [SNCFdevelopers/bootstrap-sncf#166]
Bonjour, 

Dans le bootstrap communication aucun menu ne s'ouvre en mobile.
On a le burger et la croix mais rien ne s'affiche.

Merci

![desktop](https://user-images.githubusercontent.com/26218680/52485791-f45a1800-2bb9-11e9-82d5-318a6fa4b371.PNG)
![mobile](https://user-images.githubusercontent.com/26218680/52485792-f45a1800-2bb9-11e9-862e-2005b6790766.PNG)

**Comment by diyfr** [comment]
La page concernée : 
`https://design-bootstrap.sncf.fr/docs/4.0/examples/navigation/`
résolution < `768 px` de large
L'erreur dans la console   
```error
Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLButtonElement.<anonymous> (nav-extern.js:31)
```

**Comment by arisrais** [comment]
Même problème de mon côté.

**Comment by arisrais** [comment]
Une solution de contournement possible : dans le HTML associé à la navbar il faut remplacer 
`<div data-role="menubar-menu" class="menubar-menu">`
par
`<div data-role="actionbar-menu" class="menubar-menu">`

**Comment by nicolaswurtz** [comment]
Non reproduit dans la dernière version. A rouvrir si jamais.
