### ISSUE TITLE
Spacing sur mobile

### ISSUE THREAD

**Issue by arisrais** [SNCFdevelopers/bootstrap-sncf#167]
La doc [spacing ](https://design-bootstrap.sncf.fr/docs/4.0/utilities/spacing/) indique qu'il est possible d'ajuster les spacing en fonction des breakpoints  :
 `{property}{sides}-{breakpoint}-{size} for sm, md, lg, and xl.` 

ça ne semble pas fonctionner pour le mobile (sm)

**Comment by nicolaswurtz** [comment]
Je viens de tester par exemple `ml-sm-5` pour un margin de 5 à gauche en small et ça fonctionne très bien, ras de mon côté.

Attention les classes suivant les breakpoints sont considérées « jusqu'à », si tu ne mets que `sm` par exemple, tu auras une marge gauche de 5 jusqu'à une largeur de 576px, en dessous la classe n'est plus prise en compte.

Si tu veux par exemple avoir un spacing pour mobile et un autre pour le reste il faut utiliser :
`ml-5 ml-sm-2`
Là tu auras une marge gauche de 5 jusqu'à 575px de largeur d'écran, puis une marge gauche de 2 au dessus.
