### ISSUE TITLE
Bug bloquant sur IE11 : menu

### ISSUE THREAD

**Issue by arisrais** [SNCFdevelopers/bootstrap-sncf#168]
Bonjour,

Sur le bootstrap communication impossible d'ouvrir le menu sur IE11 :

![Capture](https://user-images.githubusercontent.com/10925147/54143034-3aa8ce00-4429-11e9-9a4a-7e29221375a7.PNG)

Aucune trace d'erreur sur la console.

**Comment by diyfr** [comment]
Tu as bien ça dans le header de ta page html ?

`````html`
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
````

**Comment by arisrais** [comment]
oui j'ai bien ça !

J'ai testé sans succès avec une page html simple (sans framework) avec l'import du js + css + la meta data `<meta http-equiv="X-UA-Compatible" content="IE=edge">`

**Comment by arisrais** [comment]
Voici un exemple simple de page avec un menu
`<html lang="en">
   <head>
      
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      
      <link rel="stylesheet" href="dist/main.css">
      <title>Hello, world!</title>
   </head>
   <body>
      <header class="mastheader">
         <div class="container">
            <div class="d-flex align-items-center">
               <div class="mastheader-logo">
                  <a href="/docs" class="d-block">
                  <span class="sr-only">SNCF</span>
                  <img alt="SNCF" class="d-block" src="/assets/img/brand/sncf-logo.png" width="34" />
                  </a>
               </div>
               <h1 class="mastheader-title">Les trains en Ile-de-France de SNCF</h1>
            </div>
            <ul class="mastheader-toolbar mb-0 d-none d-md-flex">
               <li class="mastheader-toolbar-item">
                  <button type="button">AccessibilitÃ© <i class="icons-arrow-down icons-size-x5 ml-2"></i></button>
               </li>
               <li class="mastheader-toolbar-item">
                  <button type="button">Langue : Fr <i class="icons-arrow-down icons-size-x5 ml-2"></i></button>
               </li>
               <li class="mastheader-toolbar-item mastheader-toolbar-item-lg">
                  <button type="button">Tout sncf <i class="icons-options ml-3"></i></button>
               </li>
            </ul>
         </div>
      </header>
      <body>
         <div class="mastnav" data-component="mastnav">
            <div class="menubar">
               <div class="container p-md-0">
                  <h2 class="mb-0 pb-0">
                     <a href="/">
                     ITNOVEM                </a>
                  </h2>
                  <div class="menubar-menu" data-role="actionbar-menu">
                     <h3 class="mb-3 d-md-none">Menu</h3>
                     <nav class="nav">
                        <a class="nav-item" href="http://docker.local:20000/">Accueil</a><a class="nav-item" href="http://docker.local:20000/notre-entreprise/">Notre entreprise</a><button type="button" class="nav-item" data-role="main-toggle" data-target="#panel5436">Nous rejoindre<i class="icons-arrow-next icons-size-x5 ml-2"></i></button><button type="button" class="nav-item" data-role="main-toggle" data-target="#panel2155">Nous contacter<i class="icons-arrow-next icons-size-x5 ml-2"></i></button>                                    
                     </nav>
                  </div>
                  <ul class="toolbar mb-0">
                     <li class="toolbar-item no-separator-md d-md-none">
                        <button class="btn btn-burger btn-sm btn-transparent btn-color-gray toolbar-item-spacing" data-role="burger">
                        <span class="sr-only">Menu</span>
                        <i class="btn-burger-open icons-menu-burger icons-size-30px"></i>
                        <i class="btn-burger-close icons-close icons-size-30px"></i>
                        </button>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="menu" data-role="menu">
               <div class="container">
                  <div id="panel5436" class="menu-item panel primary-panel">
                     <div class="panel-inner">
                        <div class="panel-head">
                           <h3 class="h3 mb-0 pb-0" data-role="prev">
                              <i class="icons-arrow-prev icons-size-1x mr-3"></i>
                              Nous rejoindre
                           </h3>
                           <a href="#" class="btn btn-sm btn-transparent btn-color-gray panel-close" data-role="close" aria-label="Close">
                           <i class="icons-close icons-size-1x" aria-hidden="true"></i>
                           </a>
                        </div>
                        <div class="panel-content">
                           <div class="panel-lead">
                              <div class="h3 mb-4 text-white">Nous rejoindre</div>
                           </div>
                           <nav class="subnav">
                              <div class="subnav-inner">
                                 <a href="http://docker.local:20000/recrutement/" class="subnav-item">
                                 Recrutement
                                 <i class="icons-arrow-next icons-size-x5 ml-2"></i>
                                 </a>
                              </div>
                           </nav>
                        </div>
                     </div>
                  </div>
                  <div id="panel2155" class="menu-item panel primary-panel">
                     <div class="panel-inner">
                        <div class="panel-head">
                           <h3 class="h3 mb-0 pb-0" data-role="prev">
                              <i class="icons-arrow-prev icons-size-1x mr-3"></i>
                              Nous contacter
                           </h3>
                           <a href="#" class="btn btn-sm btn-transparent btn-color-gray panel-close" data-role="close" aria-label="Close">
                           <i class="icons-close icons-size-1x" aria-hidden="true"></i>
                           </a>
                        </div>
                        <div class="panel-content">
                           <div class="panel-lead">
                              <div class="h3 mb-4 text-white">Nous contacter</div>
                           </div>
                           <nav class="subnav">
                              <div class="subnav-inner">
                                 <a href="http://docker.local:20000/contact/" class="subnav-item">
                                 Contact
                                 <i class="icons-arrow-next icons-size-x5 ml-2"></i>
                                 </a>
                              </div>
                              <div class="subnav-inner">
                                 <a href="http://docker.local:20000/faq/" class="subnav-item">
                                 FAQ
                                 <i class="icons-arrow-next icons-size-x5 ml-2"></i>
                                 </a>
                              </div>
                           </nav>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <script src="dist/main.js"></script>
   </body>
</html>`

**Comment by arisrais** [comment]
Voici un exemple avec un fichier index.html + le dist bootstrap
https://drive.google.com/drive/folders/11joRCQb0PcAeWZR3dNpJbzK74Xs_GxEp?usp=sharing

Avez-vous plus d'info sur le sujet ? nous prévoyons un déploiement en production début avril :/ 

@nicolaswurtz @diyfr

**Comment by diyfr** [comment]
Tu peux vérifier manuellement le mode de compatibilité de IE11.
Tu affiches la console de développement, et dans le bandeau noir tu as un icone avec un petit écran et un numéro de version. Il semble que à la SNCF ce soit la version 7 par défaut.
Tu peux aussi changer la version dans l'onglet émulation.
Normalement la balise méta citée au dessus est sensée empêcher le mode de compatibilité.

**Comment by nicolaswurtz** [comment]
Je ferme, à rouvrir si le problème persiste toujours.
