### ISSUE TITLE
Bug menu reponsive

### ISSUE THREAD

**Issue by arisrais** [SNCFdevelopers/bootstrap-sncf#169]
Sur le bootstrap communication, sous certaines conditions le menu s'affiche pas correctement :   (libellé de menu long et/ou items de menu important) 

![Capture-menu](https://user-images.githubusercontent.com/10925147/54143437-20232480-442a-11e9-9c9f-a27ec44a52cd.PNG)

**Comment by nicolaswurtz** [comment]
Hello, tu aurais moyen de nous filer une url pour tester ? (via Teams ou mon adresse pro). Merci !

**Comment by nicolaswurtz** [comment]
J'ai corrigé une erreur dans le CSS à voir si c'était ça.
