### ISSUE TITLE
Footer - Mauvaise couleur roll le share social

### ISSUE THREAD

**Issue by jroquillet** [SNCFdevelopers/bootstrap-sncf#171]
Attendu : 
![Capture d’écran 2019-03-29 à 11 41 26](https://user-images.githubusercontent.com/46493665/55227384-a5bf1680-5217-11e9-9908-23b94cbe63fa.png)
Roll sur Facebook en #B9B9B9 vs #FFFFFF

Actuel : 
![Capture d’écran 2019-03-29 à 11 41 15](https://user-images.githubusercontent.com/46493665/55227398-b079ab80-5217-11e9-8acf-e12b0c6f68c4.png)
Couleur #0088CE sur le logo

**Comment by nicolaswurtz** [comment]
C'est un manque, ce sera dans le lot suivant avec JoliCode.

**Comment by nicolaswurtz** [comment]
Corrigé et intégré dans `dev`.
