### ISSUE TITLE
Bouton LinkedIn Share

### ISSUE THREAD

**Issue by jroquillet** [SNCFdevelopers/bootstrap-sncf#173]
Bouton LinkedIn Share, on peut se permettre de mettre directement le IN pas le IN dans un rond car ça réduit considérablement la lisibilité du logo.

Attendu : 
![Capture d’écran 2019-03-29 à 14 27 47](https://user-images.githubusercontent.com/46493665/55235862-dc545b80-522e-11e9-8338-4f710987abcc.png)

Actuel : 
![Capture d’écran 2019-03-29 à 14 26 22](https://user-images.githubusercontent.com/46493665/55235870-e5452d00-522e-11e9-8db1-ce735a3ec681.png)

**Comment by nicolaswurtz** [comment]
Corrigé.
