### ISSUE TITLE
Problème lors du build avec angular-cli (guillemets)

### ISSUE THREAD

**Issue by ggrimbert** [SNCFdevelopers/bootstrap-sncf#185]
Bonjour,

Je suis en train d'intégrer le style bootstrap-sncf dans une application sous angular 7 et j'ai un problème avec le composant breadcrumb.

Lors de la compilation j'obtiens l'erreur : 
```
ERROR in ./src/assets/bootstrap-sncf/bootstrap-sncf.min.css (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./src/assets/bootstrap-sncf/bootstrap-sncf.min.css)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /mnt/c/edevelo/workspaceTest/testBaseAngular/src/assets/bootstrap-sncf/bootstrap-sncf.min.css:1:156336: Can't resolve '/%22data:image/svg+xml;charset=utf8,%3Csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20viewBox=%270%200%2050%2050%27%3E%3Cpath%20fill=%27%23b9b9b9%27%20d=%27M40.42%2025%2017%2048.85a4.69%204.69%200%200%201-6.15%200,5.15%205.15%200%200%201-1.16-3.08%204.38%204.38%200%200%201%201.16-3.08L28.12%2025%2010.81%207.31A4.6%204.6%200%200%201%2011.58.38a5.39%205.39%200%200%201%205.77%201.16Z%27/%3E%3C/svg%3E/%22' in '/mnt/c/edevelo/workspaceTest/testBaseAngular/src/assets/bootstrap-sncf'
```

Cette erreur apparaît uniquement avec Angular 7 (pas de problème en 4). Le morceau de code mis en cause est  :
```css
.breadcrumb-item+.breadcrumb-item:before{display:inline-block;padding-right:1rem;padding-left:1rem;color:#333;content:"url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' [...]
```

Comme l'intégration du code le montre, il y a un problème avec les ```"```. En fait ils ne devraient pas exister.

Cette erreur vient de bootstrap : dans le fichier https://github.com/twbs/bootstrap/blob/v4.0.0/scss/_breadcrumb.scss (ligne 18), la variable est entre ```"```, ce qui n'est pas le bon format.

Bootstrap a corrigé le problème à partir de la version 4.1.0 (https://github.com/twbs/bootstrap/blob/v4.1.0/scss/_breadcrumb.scss)

Je confirme que cette modification dans bootstrap est la réponse au problème, je l'ai testé localement en buildant le bootstrap-sncf avec cette modification.

**Comment by nicolaswurtz** [comment]
Hello, merci pour ton retour détaillé et la solution proposée.
Pour le coup, il est prévu de monter en 4.3.1 où le bug sera corrigé. Je laisse l'issue ouverte jusqu'à ce moment-là mais je tag en wontfix (puisque ce sera corrigé par la montée de version de Bootstrap).

**Comment by ggrimbert** [comment]
Bonjour,

bonne nouvelle pour la nouvelle version de Bootstrap. Une idée de quand ce sera fait ?

**Comment by nicolaswurtz** [comment]
C'est intégré :)
