### ISSUE TITLE
Icônes différentes entre le local et la prod

### ISSUE THREAD

**Issue by kpsjocelyn** [SNCFdevelopers/bootstrap-sncf#188]
J'ai un petit soucis avec les icônes (encore :x), sur le site en local, tout fonctionne parfaitement, puis quand j'envoie le tout en production sur mon hébergement, tous les icônes sont déréglés et ne correspondent plus à leur valeur (voir capture d'écran), le cache du navigateur est pourtant purgé, ainsi que celui du serveur.
Je peux fournir un identifiant d'accès si besoin pour voir le soucis.
![Annotation 2019-05-24 162039](https://user-images.githubusercontent.com/44207118/58334533-0cd80080-7e40-11e9-8caf-9b6e1e63b91c.png)

**Comment by diyfr** [comment]
Ce que tu joues sur localhost est identique à ce qui est publié ?

**Comment by kpsjocelyn** [comment]
Exactement la même chose

**Comment by kpsjocelyn** [comment]
Bon, le problème s'est résolu tout seul, je clos l'issue.
