### ISSUE TITLE
Impossible d'importer le CSS avec webpack

### ISSUE THREAD

**Issue by slek22** [SNCFdevelopers/bootstrap-sncf#189]
Bonjour !

Je n'arrive pas à utiliser ce fork de bootstrap avec webpack. Lorsque j'importe le css minifié (https://getbootstrap.com/docs/4.3/getting-started/webpack/#importing-compiled-css)  j'ai l'erreur suivante :

```
ModuleNotFoundError
Could not find module in path: '@sncf/bootstrap-sncf.metier/dist/assets/bootstrap-sncf.min.css' relative to '/src/index.js'
```

Je soupçonne que ça vienne du point dans le nom des packages npm.

Si ça peut aider j'ai créé un CodeSandBox qui illustre le problème : https://codesandbox.io/s/agitated-davinci-nvfbn
Import du CSS de bootstrap : ✔
Import du CSS de bootstrap-sncf : ❌

Auriez-vous une idée pour contourner ce problème ?

Bonne journée !

**Comment by nicolaswurtz** [comment]
Bonjour !
Oui le chemin est `@sncf/bootstrap-sncf.metier/dist/bootstrap-sncf.min.css`
Il suffit de modifier ton fichier `index.js` et de corriger le lien (enlève `assets/` tout simplement).
Bonne journée !
