### ISSUE TITLE
[navbars] Le titre des onglets disparait

### ISSUE THREAD

**Issue by ggrimbert** [SNCFdevelopers/bootstrap-sncf#193]
Bonjour,

J'ai trouvé un comportement étrange sur le composant navbar "embarqué" (Javascript tabs behavior)

J'arrive à le reproduire avec l'exemple du site : 
 - Redimmensionner la div "actionbar" pour lui mettre une largeur de 580px
 - naviguer entre les onglets

Un flou se met sur le titre de l'onglet le plus à droite comme dans la capture ci-dessous (width: 580px)
![image](https://user-images.githubusercontent.com/15869188/60156914-dfd78e80-97ed-11e9-98c0-6f152d83c883.png)

En agrandissant, le problème disparait (le "flou" se déplace sur la droite); cependant cela empêche de centrer correctement les éléments (width 620px)
![image](https://user-images.githubusercontent.com/15869188/60157018-157c7780-97ee-11e9-80be-c659c87b93d5.png)

**Comment by nicolaswurtz** [comment]
Hello !
En fait c'est pas un bug mais une feature ;-)
Si la nav des onglets est plus petite que son contenu, alors un dégradé blanc est superposé sur la partie masquée de façon à indiquer à l'utilisateur qu'une partie du contenu n'est pas visible.
Il est possible alors de faire glisser (au doigt ou au clic) la barre d'onglets pour faire apparaître le contenu invisible — idéal sur interfaces mobiles.

C'est ainsi que le design de ce composant a été défini pour l'instant, il permet de gérer le cas de figure d'une barre d'onglet qui dépasse la largeur de l'écran (et d'éviter une superposition malheureuse des onglets).
