### ISSUE TITLE
Absence de règles css

### ISSUE THREAD

**Issue by NoMaxLand** [SNCFdevelopers/bootstrap-sncf#194]
Bonjour,

Il semblerait que certaines règles CSS présentées depuis la documentation (et bien présentes depuis les sources utilisées par la doc) ne soient pas disponibles depuis les paquets proposés au téléchargement : v4.0.0-r6.

Problème également rencontré via les sources NPM. (v4-r6 également)

ex : `.tab-content > .tab-pane` || `.tab-content > .active`

Une erreur de ma part ?

**Comment by nicolaswurtz** [comment]
Hello,
Effectivement, c'est absent des fichiers CSS, on a fait un _override_ dessus.
À la base, les seules infos qui étaient contenues dans le fichier d'origine était : 
``` css
.tab-content {
  > .tab-pane {
    display: none;
  }
  > .active {
    display: block;
  }
}
```

Ce composant a été pas mal modifié pour nos besoins en design et ces classes agissent surtout sur la partie fonctionnelle : elles sont essentielles pour le comportement JavaScript décrit ici : https://designmetier-bootstrap.sncf.fr/docs/4.0/layout/navs/#javascript-tabs-behavior

Donc, on ne les retrouve pas dans le css c'est normal.
