### ISSUE TITLE
Erreur dans les builds Webpack, demande de version non minifiée

### ISSUE THREAD

**Issue by diyfr** [SNCFdevelopers/bootstrap-sncf#195]
Sauf erreur de ma part, dans les builds Webpack :
build-*   > les css et js produit dans `_gh_pages` sont nommés avec le suffixe `.min`,  hors ils ne sont pas minifiés.    
Il faudrait différencier la config sur les commandes build-* de  dist-*  (la différence tient dans l'option webpack  `-p` qui effectue la minification) , 
Ou **[FEATURE]** produire les deux  :)

Lignes concernées sur Webpack :  
[Nom du fichier Json L35 ](https://github.com/SNCFdevelopers/bootstrap-sncf/blob/master/webpack.config.js#L35)  
[Nom du fichier css L111](https://github.com/SNCFdevelopers/bootstrap-sncf/blob/master/webpack.config.js#L111) 

Pour mémo, pour spécifier un fichier de conf particulière pour webpack, il suffit d'ajouter `--config=<nomdufichier.js>` à la commande (package.json)

**Comment by nicolaswurtz** [comment]
C'est fait, corrigé pour les builds de doc (_gh_pages), et le build contient désormais les versions non minifiées, minifiées, et la version JS épurée ;-)
