### ISSUE TITLE
V4.3.1 - ReferenceError jquery bootstrap-sncf-noext.min.js

### ISSUE THREAD

**Issue by fdalascio** [SNCFdevelopers/bootstrap-sncf#199]
Appel a jquery non défini à l'ajout du bootstrap-sncf-noext.min.js ( voir capture en PJ )

Dans mon cas jquery est pourtant ajouté avant, mais le bootstrap noext ne devrait de toute facon pas l'appeler
`<script src="js/jquery-3.4.1.min.js"></script>
<script src="bootstrap-sncf/bootstrap-sncf-noext.min.js"></script>`

![Capture](https://user-images.githubusercontent.com/53294265/61857851-32779980-aec5-11e9-990f-666a156fd5bb.PNG)

**Comment by nicolaswurtz** [comment]
Les noext ne sont pas une bonne idée hélas, on change de concept, on va intégrer la possibilité d'importer les composants un à un avec dépendances, comme le fait bootstrap original.
Je ferme du coup.
