### ISSUE TITLE
Pickers : date+time : le sélecteur d'heure doit s'afficher en même temps que le selecteur de date

### ISSUE THREAD

**Issue by nicolaswurtz** [SNCFdevelopers/bootstrap-sncf#49]
Lorsqu'on ouvre le sélecteur, les deux (date et time) doivent apparaître en même temps : 
![image](https://user-images.githubusercontent.com/6003856/40831609-bc06343a-6589-11e8-904d-fa24365ca77d.png)

**Comment by diyfr** [comment]
Mis en place en attendant de trouver une solution
https://github.com/SNCFdevelopers/bootstrap-sncf/blob/master/src/js/components/picker.js#L20
