### ISSUE TITLE
Popovers : alignement du popover possible ?

### ISSUE THREAD

**Issue by nicolaswurtz** [SNCFdevelopers/bootstrap-sncf#71]
Je m'explique. Si le bouton déclenchant la popover est aligné à droite, la popover avec sa flèche doit pouvoir suivre cet alignement. J'imagine qu'automatiquement ce sera velu, mais pouvoir le définir avec une classe ce serait suffisant.
Possible ?

Ce qu'on a : 
![image](https://user-images.githubusercontent.com/6003856/41110898-cc08b92a-6a7a-11e8-928b-81d1f3b2d03d.png)

Ce qu'il y a dans 08_1280_650_Communication : 
![image](https://user-images.githubusercontent.com/6003856/41110945-ef8d08d8-6a7a-11e8-8754-28bc63ff71ff.png)

**Comment by vdesdoigts** [comment]
Je peux passer une fonction au popover, mais malheureusement il ne prend en paramètre que `AUTO   : 'auto', TOP    : 'top', RIGHT  : 'right', BOTTOM : 'bottom', LEFT   : 'left'`.

A moins de fork Bootstrap et de modifier le comportement ou de développer le composant à part je ne peux pas avoir de position `top bottom` mixées.
